# Generated by Django 5.1.2 on 2024-10-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloTarea', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('tiempoDuracion', models.TimeField()),
                ('equipoTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mprojects.equipo')),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mprojects.proyectos')),
                ('ejecutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutor', to='mprojects.usuarios')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='mprojects.usuarios')),
            ],
        ),
    ]
