# Generated by Django 5.1.2 on 2024-10-21 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprojects', '0003_rename_fechafin_tareas_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='equipoTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mprojects.equipo'),
        ),
    ]
