# Generated by Django 5.1.2 on 2024-10-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprojects', '0004_alter_tareas_equipotrabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='tiempoDuracion',
            new_name='tiempoDuracionIfin',
        ),
        migrations.AddField(
            model_name='tareas',
            name='tiempoDuracionInicio',
            field=models.TimeField(default='1:00:00'),
            preserve_default=False,
        ),
    ]
