# Generated by Django 5.1.2 on 2024-10-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprojects', '0005_rename_tiempoduracion_tareas_tiempoduracionifin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='tiempoDuracionIfin',
            new_name='tiempoDuracionfin',
        ),
    ]
