# Generated by Django 5.1.2 on 2024-10-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprojects', '0006_rename_tiempoduracionifin_tareas_tiempoduracionfin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='tiempoDuracionfin',
            new_name='tiempoDuracionFin',
        ),
    ]
